function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "IsEven"};
	this.sidHashMap["IsEven"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "IsEven:18"};
	this.sidHashMap["IsEven:18"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<S2>"] = {sid: "IsEven:7"};
	this.sidHashMap["IsEven:7"] = {rtwname: "<S2>"};
	this.rtwnameHashMap["<S3>"] = {sid: "IsEven:12"};
	this.sidHashMap["IsEven:12"] = {rtwname: "<S3>"};
	this.rtwnameHashMap["<Root>/Inport"] = {sid: "IsEven:23"};
	this.sidHashMap["IsEven:23"] = {rtwname: "<Root>/Inport"};
	this.rtwnameHashMap["<Root>/EvenOrOdd"] = {sid: "IsEven:18"};
	this.sidHashMap["IsEven:18"] = {rtwname: "<Root>/EvenOrOdd"};
	this.rtwnameHashMap["<Root>/Outport"] = {sid: "IsEven:24"};
	this.sidHashMap["IsEven:24"] = {rtwname: "<Root>/Outport"};
	this.rtwnameHashMap["<S1>/Inport"] = {sid: "IsEven:19"};
	this.sidHashMap["IsEven:19"] = {rtwname: "<S1>/Inport"};
	this.rtwnameHashMap["<S1>/Constant"] = {sid: "IsEven:22"};
	this.sidHashMap["IsEven:22"] = {rtwname: "<S1>/Constant"};
	this.rtwnameHashMap["<S1>/If"] = {sid: "IsEven:6"};
	this.sidHashMap["IsEven:6"] = {rtwname: "<S1>/If"};
	this.rtwnameHashMap["<S1>/If Action Subsystem"] = {sid: "IsEven:7"};
	this.sidHashMap["IsEven:7"] = {rtwname: "<S1>/If Action Subsystem"};
	this.rtwnameHashMap["<S1>/If Action Subsystem1"] = {sid: "IsEven:12"};
	this.sidHashMap["IsEven:12"] = {rtwname: "<S1>/If Action Subsystem1"};
	this.rtwnameHashMap["<S1>/Math Function"] = {sid: "IsEven:1"};
	this.sidHashMap["IsEven:1"] = {rtwname: "<S1>/Math Function"};
	this.rtwnameHashMap["<S1>/Merge"] = {sid: "IsEven:16"};
	this.sidHashMap["IsEven:16"] = {rtwname: "<S1>/Merge"};
	this.rtwnameHashMap["<S1>/Outport"] = {sid: "IsEven:21"};
	this.sidHashMap["IsEven:21"] = {rtwname: "<S1>/Outport"};
	this.rtwnameHashMap["<S2>/Action Port"] = {sid: "IsEven:9"};
	this.sidHashMap["IsEven:9"] = {rtwname: "<S2>/Action Port"};
	this.rtwnameHashMap["<S2>/String Constant"] = {sid: "IsEven:11"};
	this.sidHashMap["IsEven:11"] = {rtwname: "<S2>/String Constant"};
	this.rtwnameHashMap["<S2>/Out1"] = {sid: "IsEven:10"};
	this.sidHashMap["IsEven:10"] = {rtwname: "<S2>/Out1"};
	this.rtwnameHashMap["<S3>/Action Port"] = {sid: "IsEven:13"};
	this.sidHashMap["IsEven:13"] = {rtwname: "<S3>/Action Port"};
	this.rtwnameHashMap["<S3>/String Constant"] = {sid: "IsEven:14"};
	this.sidHashMap["IsEven:14"] = {rtwname: "<S3>/String Constant"};
	this.rtwnameHashMap["<S3>/Out1"] = {sid: "IsEven:15"};
	this.sidHashMap["IsEven:15"] = {rtwname: "<S3>/Out1"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
