function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "ArrayAvg"};
	this.sidHashMap["ArrayAvg"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "ArrayAvg:11"};
	this.sidHashMap["ArrayAvg:11"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<Root>/In1"] = {sid: "ArrayAvg:2"};
	this.sidHashMap["ArrayAvg:2"] = {rtwname: "<Root>/In1"};
	this.rtwnameHashMap["<Root>/Array_Size"] = {sid: "ArrayAvg:11"};
	this.sidHashMap["ArrayAvg:11"] = {rtwname: "<Root>/Array_Size"};
	this.rtwnameHashMap["<Root>/Divide"] = {sid: "ArrayAvg:13"};
	this.sidHashMap["ArrayAvg:13"] = {rtwname: "<Root>/Divide"};
	this.rtwnameHashMap["<Root>/From"] = {sid: "ArrayAvg:6"};
	this.sidHashMap["ArrayAvg:6"] = {rtwname: "<Root>/From"};
	this.rtwnameHashMap["<Root>/From1"] = {sid: "ArrayAvg:8"};
	this.sidHashMap["ArrayAvg:8"] = {rtwname: "<Root>/From1"};
	this.rtwnameHashMap["<Root>/From2"] = {sid: "ArrayAvg:9"};
	this.sidHashMap["ArrayAvg:9"] = {rtwname: "<Root>/From2"};
	this.rtwnameHashMap["<Root>/From3"] = {sid: "ArrayAvg:12"};
	this.sidHashMap["ArrayAvg:12"] = {rtwname: "<Root>/From3"};
	this.rtwnameHashMap["<Root>/Goto"] = {sid: "ArrayAvg:7"};
	this.sidHashMap["ArrayAvg:7"] = {rtwname: "<Root>/Goto"};
	this.rtwnameHashMap["<Root>/Max of Elements"] = {sid: "ArrayAvg:3"};
	this.sidHashMap["ArrayAvg:3"] = {rtwname: "<Root>/Max of Elements"};
	this.rtwnameHashMap["<Root>/Min of Elements"] = {sid: "ArrayAvg:4"};
	this.sidHashMap["ArrayAvg:4"] = {rtwname: "<Root>/Min of Elements"};
	this.rtwnameHashMap["<Root>/Sum of Elements"] = {sid: "ArrayAvg:5"};
	this.sidHashMap["ArrayAvg:5"] = {rtwname: "<Root>/Sum of Elements"};
	this.rtwnameHashMap["<Root>/MaxOfArr"] = {sid: "ArrayAvg:1"};
	this.sidHashMap["ArrayAvg:1"] = {rtwname: "<Root>/MaxOfArr"};
	this.rtwnameHashMap["<Root>/MinOfArr"] = {sid: "ArrayAvg:10"};
	this.sidHashMap["ArrayAvg:10"] = {rtwname: "<Root>/MinOfArr"};
	this.rtwnameHashMap["<Root>/SumOfArr"] = {sid: "ArrayAvg:14"};
	this.sidHashMap["ArrayAvg:14"] = {rtwname: "<Root>/SumOfArr"};
	this.rtwnameHashMap["<Root>/AvgOfArr"] = {sid: "ArrayAvg:15"};
	this.sidHashMap["ArrayAvg:15"] = {rtwname: "<Root>/AvgOfArr"};
	this.rtwnameHashMap["<S1>:1"] = {sid: "ArrayAvg:11:1"};
	this.sidHashMap["ArrayAvg:11:1"] = {rtwname: "<S1>:1"};
	this.rtwnameHashMap["<S1>:1:2"] = {sid: "ArrayAvg:11:1:2"};
	this.sidHashMap["ArrayAvg:11:1:2"] = {rtwname: "<S1>:1:2"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
